#!/bin/sh

print_date() {
	date '+%a %d %I:%M' 
}

print_mem() {
	mem_full=$(($(sysctl -n hw.physmem) / 1024 / 1024))
	while read -r _ _ line _; do
		mem_used=${line%%M}
	done <<-EOF
		$(vmstat)
			EOF
	printf "${mem_used:-?}/${mem_full:-}M"
}

get_bat() {
	p=$(apm -l)
	printf "%s%%" "$p"
}

print_info() {
	printf '%s / %s / %s / %s\n ' "$(wk)" "$(get_bat)" "$(print_mem)" "$(date '+%a %d %I:%M')"
}

while sleep 1 ; do
	xsetroot -name "$(print_info)"
done
