#!/bin/bash

postdir=~/site/src/posts
oridir=~/site/src/origami
template="$(cat <<EOF
---
title: <++>
---
<++>
/images/<++>.jpg
EOF
)"

oritemplate="$(cat <<EOF
---
name: <++>
title: <++>
designer: <++>
paper: <++>
thumb: <++>
---
![](<++>/1.jpg)
EOF
)"

main() {
	post="$(ls ~/site/src/posts | sed '$ a\new' | dmenu -l 20)"
  #type="$(printf 'blog\norigami' | dmenu -l 20 -p Which type of post to make?)"

	if [ "$post" == "new" ]; then
		title="$(echo "" | dmenu -t -p 'title for new post: ')"
    if [ $type ==  "blog"]; then
      date="$(date +'%Y-%m-%d-')"
      newpost="$postdir/$date$title.md"
      echo "$template" >> $newpost
    elif [ $type == "origami" ]; then
      newpost="$oridir/$title.md"
      echo $oritemplate >> $newpost
    fi
    vim $newpost
	else
		vim "$postdir/$post"
	fi
}
main
